/// Resource: g_DescriptionTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\description.txt'

// Generated by TextResourceMaker 2.0, 17.12.2007 22:15:02

extern wxString g_DescriptionTxt;

/// End resource: g_DescriptionTxt
