/// Resource: g_DescriptionTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\description.txt'

// Generated by TextResourceMaker 2.0, 04.05.2008 19:58:25

extern wxString g_DescriptionTxt;

/// End resource: g_DescriptionTxt
