#include <wx/wxprec.h>

#include "html_templates.h"

/// Resource: g_TplRowTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_row.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 20:21:06

wxString g_TplRowTxt = 
	wxT(" <tr class=\"%CLASS%\">\n")
	wxT("%CELLS%\n")
	wxT(" </tr>\n") ;

/// End resource: g_TplRowTxt


/// Resource: g_TplCellTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_cell.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 20:21:06

wxString g_TplCellTxt = 
	wxT("  <td class=\"%CLASS%\">%NUMBER%</td>\n") ;

/// End resource: g_TplCellTxt


/// Resource: g_TplFileHeaderTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_file_header.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 20:21:06

wxString g_TplFileHeaderTxt = 
	wxT("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n")
	wxT("<html>\n")
	wxT("<head>\n")
	wxT(" <title>wxSudoku</title>\n")
	wxT(" <style>\n")
	wxT("  body{\n")
	wxT("   bgcolor: white;\n")
	wxT("   color: black;\n")
	wxT("  }\n")
	wxT("\n")
	wxT("  table{\n")
	wxT("   margin-top: 15px;\n")
	wxT("   margin-bottom: 15px;\n")
	wxT("   spacing: 0em;\n")
	wxT("   table-layout: fixed;\n")
	wxT("   border-collapse: collapse;\n")
	wxT("   border-spacing: 0px;\n")
	wxT("  }\n")
	wxT("\n")
	wxT("  td{\n")
	wxT("   border: 1px solid black;\n")
	wxT("   font-family: \"Comic Sans Ms\", sans-serif;\n")
	wxT("   font-size: 1.1em;\n")
	wxT("   font-weight: normal;\n")
	wxT("   width: 2em;\n")
	wxT("   height: 2em;\n")
	wxT("   padding: 0px;\n")
	wxT("   margin: 0px;\n")
	wxT("   text-align: center;\n")
	wxT("  }\n")
	wxT("\n")
	wxT("  .tb{ border-top-width: 2px; }\n")
	wxT("  .bb{ border-bottom-width: 2px; }\n")
	wxT("  .lb{ border-left-width: 2px; }\n")
	wxT("  .rb{ border-right-width: 2px; }\n")
	wxT("\n")
	wxT("  .r{ color: black; }\n")
	wxT("  .u{ color: silver; }\n")
	wxT("  .solution{ color: lime; }\n")
	wxT("  .incorrect{ color: red; }\n")
	wxT("  .inv{ bg-color: maroon; color: black; }\n")
	wxT("\n")
	wxT(" </style>\n")
	wxT("</head>\n")
	wxT("<body>\n") ;

/// End resource: g_TplFileHeaderTxt


/// Resource: g_TplFileEntryTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_file_entry.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 20:21:06

wxString g_TplFileEntryTxt = 
	wxT("\n")
	wxT("\n")
	wxT("<!--\n")
	wxT("<sudoku>\n")
	wxT(" <app name=\"wxSudoku\" version=\"2.3\" author=\"Thomas Glaessle\">\n")
	wxT(" <content>\n")
	wxT("%SAVE%\n")
	wxT(" </content>\n")
	wxT("</sudoku>\n")
	wxT("-->\n")
	wxT("\n")
	wxT("<table align=\"center\">\n")
	wxT("\n")
	wxT("%ROWS%\n")
	wxT("\n")
	wxT("</table>\n")
	wxT("\n") ;

/// End resource: g_TplFileEntryTxt


/// Resource: g_TplFileFooterTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_file_footer.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 20:21:06

wxString g_TplFileFooterTxt = 
	wxT("\n")
	wxT("</body>\n")
	wxT("</html>\n") ;

/// End resource: g_TplFileFooterTxt
