#ifndef __HTML_TEMPLATES_H__INCLUDED__
#define __HTML_TEMPLATES_H__INCLUDED__

#include <wx/string.h>

/// Resource: g_TplRowTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\tpl_row.txt'

// Generated by TextResourceMaker 2.0, 07.01.2008 20:04:58

extern wxString g_TplRowTxt;

/// End resource: g_TplRowTxt


/// Resource: g_TplFileTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\tpl_file.txt'

// Generated by TextResourceMaker 2.0, 07.01.2008 20:04:58

extern wxString g_TplFileTxt;

/// End resource: g_TplFileTxt


/// Resource: g_TplCellTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\tpl_cell.txt'

// Generated by TextResourceMaker 2.0, 07.01.2008 20:04:58

extern wxString g_TplCellTxt;

/// End resource: g_TplCellTxt


#endif // __HTML_TEMPLATES_H__INCLUDED__
