#include <wx/wxprec.h>

#include "html_templates.h"

/// Resource: g_TplRowTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\tpl_row.txt'

// Generated by TextResourceMaker 2.0, 07.01.2008 20:04:58

wxString g_TplRowTxt = 
	wxT(" <tr class=\"%CLASS%\">\n")
	wxT("%CELLS%\n")
	wxT(" </tr>\n") ;

/// End resource: g_TplRowTxt


/// Resource: g_TplFileTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\tpl_file.txt'

// Generated by TextResourceMaker 2.0, 07.01.2008 20:04:58

wxString g_TplFileTxt = 
	wxT("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n")
	wxT("<html>\n")
	wxT("<head>\n")
	wxT(" <title>wxSudoku</title>\n")
	wxT(" <style>\n")
	wxT("  body{\n")
	wxT("   bgcolor: white;\n")
	wxT("   color: black;\n")
	wxT("  }\n")
	wxT("  \n")
	wxT("  table{\n")
	wxT("   margin-top: 15px;\n")
	wxT("   margin-bottom: 15px;\n")
	wxT("   spacing: 0em;\n")
	wxT("   table-layout: fixed;\n")
	wxT("   border-collapse: collapse;\n")
	wxT("   border-spacing: 0px;\n")
	wxT("  }\n")
	wxT("  \n")
	wxT("  td{\n")
	wxT("   border: 1px solid black;\n")
	wxT("   font-family: \"Comic Sans Ms\", sans-serif;\n")
	wxT("   font-size: 1.1em;\n")
	wxT("   font-weight: normal;\n")
	wxT("   width: 2em;\n")
	wxT("   height: 2em;\n")
	wxT("   padding: 0px;\n")
	wxT("   margin: 0px;\n")
	wxT("   text-align: center;\n")
	wxT("  }\n")
	wxT("  \n")
	wxT("  .topborder{ border-top-width: 2px; }\n")
	wxT("  .bottomborder{ border-bottom-width: 2px; }\n")
	wxT("  .leftborder{ border-left-width: 2px; }\n")
	wxT("  .rightborder{ border-right-width: 2px; }\n")
	wxT("  \n")
	wxT("  .riddle{ color: black; }\n")
	wxT("  .user{ color: silver; }\n")
	wxT("  .solution{ color: lime; }\n")
	wxT("  .incorrect{ color: red; }\n")
	wxT("  .invalid{ bg-color: maroon; color: black; }\n")
	wxT("  \n")
	wxT(" </style>\n")
	wxT("</head>\n")
	wxT("<body>\n")
	wxT("\n")
	wxT("<table align=\"center\">\n")
	wxT("\n")
	wxT("%ROWS%\n")
	wxT("\n")
	wxT("</table>\n")
	wxT("\n")
	wxT("</body>\n")
	wxT("</html>\n") ;

/// End resource: g_TplFileTxt


/// Resource: g_TplCellTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.2\tpl_cell.txt'

// Generated by TextResourceMaker 2.0, 07.01.2008 20:04:58

wxString g_TplCellTxt = 
	wxT("  <td class=\"%CLASS%\">%NUMBER%</td>\n") ;

/// End resource: g_TplCellTxt

