#ifndef __HTML_TEMPLATES_H__INCLUDED__
#define __HTML_TEMPLATES_H__INCLUDED__

#include <wx/string.h>

/// Resource: g_TplRowTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_row.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 18:47:05

extern wxString g_TplRowTxt;

/// End resource: g_TplRowTxt


/// Resource: g_TplCellTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_cell.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 18:47:05

extern wxString g_TplCellTxt;

/// End resource: g_TplCellTxt


/// Resource: g_TplFileHeaderTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_file_header.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 18:47:04

extern wxString g_TplFileHeaderTxt;

/// End resource: g_TplFileHeaderTxt


/// Resource: g_TplFileEntryTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_file_entry.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 18:47:05

extern wxString g_TplFileEntryTxt;

/// End resource: g_TplFileEntryTxt


/// Resource: g_TplFileFooterTxt from 'D:\coding\c++ projects\0013 wxSudoku 2.3\tpl_file_footer.txt'

// Generated by TextResourceMaker 2.0, 08.05.2008 18:47:05

extern wxString g_TplFileFooterTxt;

/// End resource: g_TplFileFooterTxt


#endif // __HTML_TEMPLATES_H__INCLUDED__


